name: Deploy Resume WebApp to EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: prod
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload files to S3
        run: |
          cp index-ec2.html index.html
          cp style-ec2.css style.css
          aws s3 sync . s3://${{ secrets.S3_BUCKET }}/ --exclude ".git/*" --exclude ".github/*"

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "sudo apt-get -y update",
              "sudo apt-get install -y apache2",
              "sudo systemctl daemon-reload",
              "sudo systemctl start apache2",
              "sudo systemctl enable apache2",
              "sudo rm -rf /var/www/html/*",
              "sudo aws s3 sync s3://${{ secrets.S3_BUCKET }}/ /var/www/html/"
            ]' \
            --region ${{ secrets.AWS_REGION }}
